export {};

declare global {
  namespace JSX {
    interface IntrinsicElements {
      [key: string]: any
    }
  }
}

// @ts-ignore
import("fusion-wasm").then(({ default: Fusion }: any) => {
  function Note(props: any) {
    const log = () => console.log("clicked: " + props.name);
    return <note-name className="note" onClick={log}>✅ {props.name}</note-name>
  };

  function App(props: any) {
    const notes = props.notes;
    const [a, setA] = Fusion.useState({ a: "a "});
    const [b, setB] = Fusion.useState("B");
    const onClickA = () => {
      setA({ a: a.a + "H" });
    };
    const onClickB = () => {
      setB(b + "Z");
    };
    return (
      <main>
        <h2>Melhores séries</h2>
        <span>A: {a.a} <button onClick={onClickA}>A</button></span>
        <br></br>
        <span>B: {b} <button onClick={onClickB}>B</button></span>
        {
          notes.map((name: string) =>{
            return <Note name={name} />
          })
        }
        <status>it's {props.status}</status>
      </main>
    );
  }

  let notes = [
    "Cobra Kai",
    "Dark",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
    "Game of Thrones",
  ];

  Fusion.render(<App status="WORKING" notes={notes} />, document.getElementById("root") as any);
  
  setTimeout(() => {
    notes.push("Jane the virgin");
    Fusion.render(<App status="UPDATING" notes={notes} />, document.getElementById("root") as any);
  }, 5000);
});
